<?php
/**
 * Show changes for one or more entities
 * @param mixed[] $changes
 * @param int|null $maxRows
 * @param bool $showEntity whether or not to show the entity column
 */
use Cake\Utility\Text;
use GeoIp2\Database\Reader;
use GeoIp2\Model\City;

?>
<div class="responsive-table">
<table class="table">
<?php $standingTimeString = '';
$showEntity = isset($this->showEntity) ? (bool)$this->showEntity : true;
$maxRows = $this->maxRows ?? null;
$limitRows = isset($maxRows);
$counter = 0;
foreach ($this->changes as $row):
    ++$counter;
    if ($limitRows && $counter > $this->maxRows) {
        break;
    }
	$cTimeString = $this->dateFormat($row['updatedOn'], IntlDateFormatter::SHORT, IntlDateFormatter::NONE);
	if ($cTimeString != $standingTimeString) :
	$standingTimeString = $cTimeString;?>
	<thead>
	<tr>
		<th><?php echo $cTimeString;?></th><?php
		if ($showEntity):?>
			<th><?php echo $this->translate("Entity");?></th><?php
		endif;?>
		<th><?php echo $this->translate("Field");?></th>
		<th><?php echo $this->translate("Old Value");?></th>
		<th><?php echo $this->translate("New Value");?></th>
	</tr>
	</thead>
	<?php endif;
	$geoText = null;
	if (isset($row['ipAddress'])) {
        /** @var City $record */
        $record = $this->geoIp2City($row['ipAddress']);
    	if (isset($record)) {
    	    $geoText = $this->escapeHtml($record->city->name) . ", " . $this->escapeHtml($record->country->name);
    	}
	}?>
	<tr>
    	<td><span <?php if ($geoText):?>data-toggle="tooltip" data-placement="bottom" data-container="body"
    	title="<?php echo $this->escapeHtmlAttr($geoText);
    	endif;?>"><?php if (is_array($row['updatedBy'])) {
    	    echo $this->escapeHtml($row['updatedBy']['username']);
    	}?></span>
    	</td><?php
    	if ($showEntity):?>
		<td><?php
            if (isset($row['object'])) {
                $formattedEntity = $this->formatEntity($row['entityType'], $row['object'],
                    [
                        'displayEditPencil' => !isset($row['object']['isDeleted']),
                        'failSilently' => true,
                    ]);
                echo ! empty($formattedEntity) ? $formattedEntity : $this->escapeHtml($row['entityType']);
            }?></td><?php
        endif;?>
		<td><?php echo $this->escapeHtml($row['field']);?></td>
		<td><?php echo $this->escapeHtml(Text::truncate($row['oldValue'],150));?></td>
		<td><?php echo $this->escapeHtml(Text::truncate($row['newValue'],150));?></td>
	</tr>
<?php endforeach; ?>
</table>
</div>