<?php
/**
 * Show changes for one or more entities
 * @param mixed[] $changes
 * @param int|null $maxRows
 * @param bool $showEntity whether or not to show the entity column
 */
use Cake\Utility\Text;
?>
<div class="responsive-table">
<table class="table">
<?php $standingTimeString = '';
$showEntity = isset($this->showEntity) ? (bool)$this->showEntity : true;
$maxRows = isset($this->maxRows) ? $this->maxRows : null;
$limitRows = isset($maxRows);
$counter = 0;
foreach ($this->changes as $row):
    ++$counter;
    if ($limitRows && $counter > $this->maxRows) {
        break;
    }
	$cTimeString = $this->dateFormat($row['updatedOn'], IntlDateFormatter::SHORT, IntlDateFormatter::NONE);
	if ($cTimeString != $standingTimeString) :
	$standingTimeString = $cTimeString;?>
	<thead>
	<tr>
		<th><?php echo $cTimeString;?></th><?php
		if ($showEntity):?>
			<th><?php echo $this->translate("Entity");?></th><?php
		endif;?>
		<th><?php echo $this->translate("Field");?></th>
		<th><?php echo $this->translate("Old Value");?></th>
		<th><?php echo $this->translate("New Value");?></th>
	</tr>
	</thead>
	<?php endif;
	$geoText = null;
	if (isset($row['ipAddress'])) {
    	$geoText = '';
        $geo = $this->geoip($row['ipAddress']);
    	if ($geo && $geo->getCity()) {
    	    $geoText .= ' ' . mb_convert_encoding($geo->getCity(),"UTF-8","Windows-1252").", ";
    	}
    	if ($geo && $geo->getCountryName()) {
    	    $geoText .= mb_convert_encoding($geo->getCountryName(),"UTF-8","Windows-1252");
    	}
	}?>
	<tr>
    	<td><span <?php if ($geoText):?>data-toggle="tooltip" data-placement="bottom" data-container="body"
    	title="<?php echo $this->escapeHtmlAttr($geoText);
    	endif;?>"><?php echo $this->escapeHtml($row['updatedBy']['username'])?></span>
    	</td><?php
    	if ($showEntity):?>
		<td><?php
            if (isset($row['object']) && !is_null($row['object'])) {

                echo $this->formatEntity($row['entityType'], $row['object'],
                    [
                        'displayEditPencil' => !isset($row['object']['isDeleted']),
                        'failSilently' => true,
                    ]);
            }?></td><?php
        endif;?>
		<td><?php echo $this->escapeHtml($row['field']);?></td>
		<td><?php echo $this->escapeHtml(Text::truncate($row['oldValue'],150));?></td>
		<td><?php echo $this->escapeHtml(Text::truncate($row['newValue'],150));?></td>
	</tr>
<?php endforeach; ?>
</table>
</div>