<?php use Patres\Model\EntityProblem;
/**
 * @var EntityProblem[] $problems
 */
$problems = $this->problems;
if (isset($this->isSimulation) && $this->isSimulation):?>
<h1><?php echo $this->translate('Simulated auto-fix');?></h1>
<p><?php echo $this->translate('This is a simulation of some data problems that could be automatically. Do you wish to proceed?');?></p>
<?php $form = $this->form;
$form->prepare();
echo $this->form()->openTag($form);
echo $this->formHidden($form->get('security'));
echo $this->formRow($form->get('submit'));
echo $this->form()->closeTag();
elseif (isset($this->isSimulation) && !$this->isSimulation):?>
<h1><?php echo $this->translate('Attempted auto-fix');?></h1>
<p><?php echo $this->translate('We have attempted to auto-fix what we could. Below are the affected rows.');?></p>
<?php endif;?>
<p><strong><?php echo $this->translate('Total problems')?>:</strong>&nbsp;<?php echo count($problems);?></p>
<table class="table">
	<thead>
	<tr>
	<th><?php echo $this->translate('Entity');?></th>
	<th><?php echo $this->translate('Problem');?></th>
	</tr>
	</thead>
	<tbody>
<?php foreach ($problems as $entity) :?>
<tr>
	<td><?php echo $this->formatEntity($entity->getEntity(), $entity->getData(), ['displayEditPencil' => true]);?></td>
	<td class="<?php echo $entity->getProblemTextClass()?>"><?php
	echo $this->escapeHtml($this->translate($entity->getProblemText(), $entity->getTranslatorTextDomain()));?></td>
</tr>
<?php endforeach;?>
	</tbody>
</table>