<?php
/**
 * Show changes for one or more entities
 * @param mixed[] $changes
 * @param int|null $maxRows
 * @param bool $showEntity whether or not to show the entity column
 */
$headText = 'View Changes';
$this->headTitle($headText);
?>
<h1><?php echo $this->translate("Database edits")?></h1><?php
echo $this->partial('changes-table', [
    'changes' => $this->changes,
    'maxRows' => isset($this->maxRows) ? $this->maxRows : null,
    'showEntity' => isset($this->showEntity) ? $this->showEntity : true,
]);
?>