<?php
use SionModel\Form\CommentForm;

/**
 * Partial for generating markup for a new comment
 * @param \SionModel\Form\CommentForm $form
 * @param string $entity
 * @param number $entityId
 * @param string $inLanguage (optional) @todo add message to user to let them know what language we're expecting
 * @param array $options
 */
/** @var \SionModel\Form\CommentForm $form */
if (isset($this->form)) { //assume the user already filled in all the variables
    if (!$form instanceof CommentForm) {
        throw new \Exception('Invalid comment form');
    }
    $form = $this->form; 
} else {
    $form = new CommentForm();
    if (!isset($this->entity) || !isset($this->entityId)) {
        throw new \Exception('Missing entity or entityId parameter for comment form');
    }
    $urlParams = ['entity' => $this->entity, 'entity_id' => $this->entityId];
    if (isset($this->kind)) {
        if (!is_string($this->kind) || !isset(\SionModel\Db\Model\PredicatesTable::COMMENT_KINDS[$this->kind])) {
            throw new \Exception('Invalid kind parameter');
        }
        $urlParams['kind'] = $this->kind;
    }
    if (isset($this->redirect)) {
        $form->get('redirect')->setValue($this->redirect);
    } elseif (null === $form->get('redirect')->getValue()) {
        throw new \Exception('Missing redirect parameter for comment form');
    }
    $form->setAttribute('action', $this->url('comments/create', $urlParams));
}
$form->prepare();
?>

<div class="row"> <!-- comment create row -->
<div class="col-md-12">
<div class="panel panel-default" id="commentCreatePanel">
    <div class="panel-heading">
        <h3 class="panel-title"><i class="fa fa-paper-plane-o"></i> <?= $this->translate($form->get('comment')->getLabel()); ?></h3>
    </div>
    <div class="panel-body">
    <div>
    	<?php 
    	   //ugly hack to get around limitations in TwbBundle\Form\View\Helper\TwbBundleForm
    	   $openTag = $this->form()->openTag($form);
           echo str_replace("form-horizontal","form",$openTag);?>
        <div class="form-group">
            <?= $this->formElement($form->get('comment'));?>
        </div>
        <?php echo $this->formRow($form->get('redirect'));
        echo $this->formRow($form->get('security'));
        echo $this->formRow($form->get('submit'));?>
        <!-- <button type="submit" class="btn btn-primary"><i class="fa fa-reply"></i> Submit</button> -->
	<?= $this->form()->closeTag();?>
    </div>
    </div> <!-- notes panel body -->
</div> <!-- comment create panel -->
</div> <!-- comment create column 12 -->
</div> <!-- comment create row -->