<?php
namespace SionModel;

return [
    'view_helpers' => [
        'factories' => [
            'address'				=> 'SionModel\Service\AddressFactory',
            'editPencil'			=> 'SionModel\Service\EditPencilFactory',
            'formatEntity'		    => 'SionModel\Service\FormatEntityFactory',
            'touchButton'			=> 'SionModel\Service\TouchButtonFactory',
        ],
        'invokables' => [
            'formRow'		        => 'SionModel\Form\View\Helper\SionFormRow',
            'dayFormat'             => 'SionModel\I18n\View\Helper\DayFormat',
            'debugEncoding'			=> 'SionModel\View\Helper\DebugEncoding',
            'diffForHumans'         => 'SionModel\View\Helper\DiffForHumans',
            'email'					=> 'SionModel\View\Helper\Email',
            'formatUrlObject'       => 'SionModel\View\Helper\FormatUrlObject',
            'jshrink'		        => 'SionModel\View\Helper\Jshrink',
            'shortDateRange'		=> 'SionModel\View\Helper\ShortDateRange',
            'telephone'				=> 'SionModel\View\Helper\Telephone',
            'telephoneList'			=> 'SionModel\View\Helper\TelephoneList',
            'tooltip'               => 'SionModel\View\Helper\Tooltip',
		],
	],
    'validators' => [
        'invokables' => [
            'Skype'     => 'SionModel\Validator\Skype',
            'Twitter'   => 'SionModel\Validator\Twitter',
            'Instagram' => 'SionModel\Validator\Instagram',
            'Phone'     => 'SionModel\Validator\Phone',
            'Slack'     => 'SionModel\Validator\Slack',
         ],
    ],
    'form_elements' => [
        'invokables' => [
            'Phone' => 'SionModel\Form\Element\Phone',
        ],
    ],
    'view_manager' => [
        'template_path_stack' => [
            'sion-model' => __DIR__ . '/../view',
        ],
    ],
    'service_manager' => [
        'factories' => [
            'CountryValueOptions'                   => 'SionModel\Service\CountryValueOptionsFactory',
            'SionModel\Config'                      => 'SionModel\Service\ConfigServiceFactory',
            'SionModel\FilesTable'                  => 'SionModel\Service\FilesTableFactory',
            'SionModel\Form\SuggestForm'            => 'SionModel\Service\SuggestFormFactory',
            'SionModel\PersistentCache'             => 'SionModel\Service\PersistentCacheFactory',
            'SionModel\Problem\ProblemTable'        => 'SionModel\Service\ProblemTableFactory',
            'SionModel\Service\EntitiesService'     => 'SionModel\Service\EntitiesServiceFactory',
            'SionModel\Service\ProblemService'      => 'SionModel\Service\ProblemServiceFactory',
            'SionModel\Service\AllChanges'          => 'SionModel\Service\AllChangesServiceFactory',
        ],
    ],
    'sion_model' => [
        'file_directory'            => 'data/files',
        'public_file_directory'     => 'public/files',
        'max_items_to_cache'        => 2,
        'changes_max_rows'          => 500,
        'changes_show_all'          => true,
        'api_keys'                  => [], //users should specify long, random authentication keys here
        'post_place_line_format'    => ':zip :cityState',
        'post_place_line_format_by_country' => [
            'US' => ':cityState :zip',
            'CL' => ':cityState :zip',
        ],
        'url_map'                   => [ //@todo clarify this, for general users
            'g+' => [
                'android'   => '%s',
                'ios'       => '%s',
                'default'   => '%s',
                'logo'      => 'img/g+.png',
                'label'     => 'G+',
            ],
            'skype' => [
                'android'   => 'skype:%s?call',
                'ios'       => 'skype:%s?call',
                'default'   => 'skype:%s?call',
                'logo'      => 'img/skype.png',
                'userKey'   => 'skypeUser',
                'label'     => 'Skype',
            ],
            'instagram' => [
                'android'   => 'https://www.instagram.com/%s',
                'ios'       => 'instagram://user?username=%s',
                'default'   => 'https://www.instagram.com/%s',
                'logo'      => 'img/instagram.png',
                'userKey'   => 'instagramUser',
                'label'     => 'Instagram',
            ],
            'slack' => [
                'android'   => 'https://schoenstatt-fathers.slack.com/messages/%s/',
                'ios'       => 'https://schoenstatt-fathers.slack.com/messages/%s/',
                'default'   => 'https://schoenstatt-fathers.slack.com/messages/%s/',
                'logo'      => 'img/slack.png',
                'userKey'   => 'slackUser',
                'label'     => 'Slack',
            ],
            'twitter' => [
                'android'   => 'https://twitter.com/%s',
                'ios'       => 'twitter://user?screen_name=%s',
                'default'   => 'https://twitter.com/%s',
                'logo'      => 'img/twitter.png',
                'userKey'   => 'twitterUser',
                'label'     => 'Twitter',
            ],
            'facebook' => [
                'android'   => '%s',
                'ios'       => '%s',
                'default'   => '%s',
                'logo'      => 'img/facebook.png',
                'userKey'   => 'facebookUrl',
                'label'     => 'Facebook',
            ],
            'wikipedia' => [
                'android'   => '%s',
                'ios'       => '%s',
                'default'   => '%s',
                'logo'      => 'img/wikipedia.png',
                'label'     => 'Wikipedia',
            ],
            'blog' => [
                'logo'      => 'img/blogger.png',
                'label'     => 'Blog',
            ],
        ],
//         'persistent_cache_config' => [
//             'adapter' => [
//                 'name' => 'filesystem',
//                 'options' => [
//                     'dirLevel' => 2,
//                     'cacheDir' => 'data/cache',
//                     'dirPermission' => 0755,
//                     'filePermission' => 0666,
//                     'namespaceSeparator' => '-db-'
//                 ],
//             ],
//             'plugins' => ['serializer'],//   - See more at: https://arjunphp.com/zend-framework-2-cache-example/#sthash.1P0kgSma.dpuf
    //         ],
        'entities' => [
            /**
             * For more information on entity config:
             * @see \SionModel\Entity\Entity
             */
            'file' => [
                'name'									=> 'file',
                'table_name' 							=> 'files',
                'table_key' 							=> 'FileId',
                'entity_key_field'               		=> 'fileId',
                'sion_model_class'               		=> 'SionModel\Db\Model\FilesTable',
                'get_object_function' 					=> 'getFile',
                'get_objects_function'               	=> 'getFiles',
//                 'format_view_helper'                    => 'formatEvent',
                'required_columns_for_creation' 		=> [
                    'originalFileName',
                    'mimeType',
                    'size',
                    'sha1',
                ],
                'name_field'               				=> 'originalFileName',
                'name_field_is_translateable'           => false,
//                 'country_field'               			=> 'country',
                'text_columns'               			=> [],
                'many_to_one_update_columns'     		=> [
//                     'email'	=> 'contactInfo',
//                     'cell'	=> 'contactInfo',
                ],
                'report_changes'               			=> true,
                'index_route'               			=> 'files',
//                 'index_template'               			=> 'project/events/index',
//                 'default_route_key'                     => 'file_id',
//                 'show_action_template'               	=> 'project/events/show',
//                 'show_route' 							=> 'files/files',
//                 'show_route_key' 						=> 'file_id',
//                 'show_route_key_field' 					=> 'fileId',
//                 'edit_action_form'               		=> 'SionModel\Form\EditFileForm',
//                 'edit_action_template'               	=> 'project/events/edit',
//                 'edit_route'               				=> 'events/event/edit',
//                 'edit_route_key'               			=> 'file_id',
//                 'edit_route_key_field'           		=> 'fileId',
//                 'create_action_form'              		=> 'SionModel\Form\UploadFileForm',
//                 'create_action_valid_data_handler'		=> 'createEvent',
//                 'create_action_redirect_route'         	=> 'files/file',
//                 'create_action_redirect_route_key'    	=> 'file_id',
//                 'create_action_redirect_route_key_field'=> 'fileId',
//                 'create_action_template'           		=> 'project/events/create',
//                 'touch_default_field'               	=> 'fileId',
//                 'touch_field_route_key'           		=> 'event_id',
//                 'touch_json_route'               		=> 'events/event/touch',
//                 'touch_json_route_key'            		=> 'file_id',
                'database_bound_data_preprocessor' 		=> 'preprocessFile',
//                 'database_bound_data_postprocessor' 	=> 'postprocessEvent',
//                 'moderate_route' 						=> 'events/event/moderate',
//                 'moderate_route_entity_key' 			=> 'file_id',
//                 'has_dedicated_suggest_form' 			=> false,
//                 'suggest_form'               			=> 'Project\Form\SuggestEventForm',
                'enable_delete_action' 					=> true,
//                 'delete_action_acl_resource' 			=> 'event_:id',
//                 'delete_action_acl_permission' 			=> 'delete_event',
//                 'delete_action_redirect_route' 			=> 'events',
                'update_columns' 						=> [
                    'fileId'                => 'FileId',
                    'storeFileName'         => 'StoreFileName',
                    'originalFileName'      => 'OriginalFileName',
                    'fileKind'              => 'FileKind',
                    'description'           => 'Description',
                    'size'                  => 'Size',
                    'sha1'                  => 'Sha1',
                    'contentTags'           => 'ContentTags',
                    'structureTags'         => 'StructureTags',
                    'mimeType'              => 'MimeType',
                    'isPublic'              => 'IsPublic',
                    'isEncrypted'           => 'IsEncrypted',
                    'encryptedEncryptionKey'=> 'EncryptedEncryptionKey',
                    'createdOn'             => 'CreatedOn',
                    'createdBy'             => 'CreatedBy',
                    'updatedOn'             => 'UpdatedOn',
                    'createdBy'             => 'UpdatedBy',
                ],
            ],
            'file-entity' => [
                'name'									=> 'file-entity',
                'table_name' 							=> 'files_entities',
                'table_key' 							=> 'FileEntityId',
                'entity_key_field'               		=> 'fileEntityId',
                'sion_model_class'               		=> 'SionModel\Db\Model\FilesTable',
                'get_object_function' 					=> 'getFileEntity',
                'get_objects_function'               	=> 'getFileEntities',
                //                 'format_view_helper'                    => 'formatEvent',
                'required_columns_for_creation' 		=> [
                    'title'
                ],
                'name_field'               				=> 'fileName',
                'name_field_is_translateable'           => false,
//                 'country_field'               			=> 'country',
                'text_columns'               			=> [],
                'many_to_one_update_columns'     		=> [
//                     'email'	=> 'contactInfo',
//                     'cell'	=> 'contactInfo',
                ],
                'report_changes'               			=> true,
                'index_route'               			=> 'files',
//                 'index_template'               			=> 'project/events/index',
                'default_route_key'                     => 'file_id',
//                 'show_action_template'               	=> 'project/events/show',
                'show_route' 							=> 'files/files',
                'show_route_key' 						=> 'file_id',
                'show_route_key_field' 					=> 'fileId',
                'edit_action_form'               		=> 'SionModel\Form\EditFileForm',
                'edit_action_template'               	=> 'project/events/edit',
                'edit_route'               				=> 'files/file/edit',
                'edit_route_key'               			=> 'file_id',
                'edit_route_key_field'           		=> 'fileId',
                'create_action_form'              		=> 'SionModel\Form\UploadFileForm',
//                 'create_action_valid_data_handler'		=> 'createEvent',
                'create_action_redirect_route'         	=> 'files/file',
                'create_action_redirect_route_key'    	=> 'file_id',
                'create_action_redirect_route_key_field'=> 'fileId',
//                 'create_action_template'           		=> 'project/events/create',
//                 'touch_default_field'               	=> 'fileId',
//                 'touch_field_route_key'           		=> 'event_id',
//                 'touch_json_route'               		=> 'events/event/touch',
//                 'touch_json_route_key'            		=> 'file_id',
//                 'database_bound_data_preprocessor' 		=> 'preprocessEvent',
//                 'database_bound_data_postprocessor' 	=> 'postprocessEvent',
//                 'moderate_route' 						=> 'events/event/moderate',
//                 'moderate_route_entity_key' 			=> 'file_id',
//                 'has_dedicated_suggest_form' 			=> false,
//                 'suggest_form'               			=> 'Project\Form\SuggestEventForm',
                'enable_delete_action' 					=> true,
                'delete_action_acl_resource' 			=> 'event_:id',
                'delete_action_acl_permission' 			=> 'delete_event',
                'delete_action_redirect_route' 			=> 'events',
                'update_columns' 						=> [
                    'fileId'        => 'FileId',
                    'fileName'      => 'FileName',
                    'mimeType'      => 'MimeType',
                    'extension'     => 'Extension',
                    'description'   => 'Description',
                    'fullText'      => 'FullText',
                    'size'          => 'Size',
                    'md5'           => 'MD5',
                    'contentTags'   => 'ContentTags',
                    'structureTags' => 'StructureTags',
                    'createdOn'     => 'CreatedOn',
                    'createdBy'     => 'CreatedBy',
                    'updatedOn'     => 'UpdatedOn',
                    'createdBy'     => 'UpdatedBy',
                ],
            ],
        ],
    ],
    'controllers' => [
        'invokables' => [
            'SionModel\Controller\Sion' => 'SionModel\Controller\SionModelController',
        ],
    ],
    'router' => [
        'routes' => [
            'sion-model' => [
                'type'    => 'Literal',
                'options' => [
                    'route'    => '/sm',
                    'defaults' => [
                        'controller' => 'SionModel\Controller\Sion',
                        'action'     => 'index',
                    ],
                ],
                'may_terminate' => false,
                'child_routes' => [
                    'clear-persistent-cache' => [
                        'type'    => 'Literal',
                        'options' => [
                            'route'    => '/clear-persistent-cache',
                            'defaults' => [
                                'action'     => 'clearPersistentCache',
                            ],
                        ],
                    ],
                    'data-problems' => [
                        'type'    => 'Literal',
                        'options' => [
                            'route'    => '/data-problems',
                            'defaults' => [
                                'action'     => 'dataProblems',
                            ],
                        ],
                    ],
                    'auto-fix-data-problems' => [
                        'type'    => 'Literal',
                        'options' => [
                            'route'    => '/auto-fix-data-problems',
                            'defaults' => [
                                'action'     => 'autoFixDataProblems',
                            ],
                        ],
                    ],
                    'view-changes' => [
                        'type'    => 'Literal',
                        'options' => [
                            'route'    => '/view-changes',
                            'defaults' => [
                                'action'     => 'viewChanges',
                            ],
                        ],
                    ],
                    'delete-entity' => [
                        'type'    => 'Segment',
                        'options' => [
                            'route'    => '/delete/:entity/:entity_id',
                            'defaults' => [
                                'action' => 'deleteEntity',
                            ],
                            'constraints' => [
                                'entity_id' => '[0-9]{1,5}',
                                'entity' => '[a-zA-Z_-]{1,25}',
                            ],
                        ],
                    ],
                ],
            ],
        ],
    ],
];
