CREATE TABLE `project_problems` 
( `ProblemId` INT NOT NULL AUTO_INCREMENT , 
`Project` VARCHAR(50) NOT NULL , 
`Entity` VARCHAR(50) NOT NULL , 
`EntityId` INT NOT NULL , 
`Problem` VARCHAR(50) NOT NULL , 
`Severity` VARCHAR(20) NULL DEFAULT NULL , 
`IgnoredOn` DATETIME NULL DEFAULT NULL , 
`IgnoredBy` INT NULL DEFAULT NULL , 
`ResolvedOn` DATETIME NULL DEFAULT NULL , 
`ResolvedBy` INT NULL DEFAULT NULL , 
`UpdatedOn` DATETIME NULL DEFAULT NULL , 
`UpdatedBy` INT NULL DEFAULT NULL , 
`CreatedOn` DATETIME NULL DEFAULT NULL , 
`CreatedBy` INT NULL DEFAULT NULL , 
PRIMARY KEY (`ProblemId`)) 
ENGINE = InnoDB CHARACTER SET utf8 COLLATE utf8_general_ci;